import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar for the User Manual (plugin id: 'user')
const sidebars: SidebarsConfig = {
  userManualSidebar: [
    // Portada del manual
    'index',
    // Secciones
    {
      type: 'category',
      label: 'Administrador',
      items: [{type: 'autogenerated', dirName: 'administrador'}],
    },
    {
      type: 'category',
      label: 'Patólogo',
      items: [{type: 'autogenerated', dirName: 'patologo'}],
    },
    {
      type: 'category',
      label: 'Facturación',
      items: [{type: 'autogenerated', dirName: 'facturacion'}],
    },
    {
      type: 'category',
      label: 'Auxiliar Administrativo',
      items: [{type: 'autogenerated', dirName: 'auxiliar-administrativo'}],
    },
  ],
};

export default sidebars;