import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Explicit sidebar structure to control order and visibility in the panel
  tutorialSidebar: [
    // Intro page
    'introduccion',

    // Front-End
    {
      type: 'category',
      label: 'Front-End',
      items: [{type: 'autogenerated', dirName: 'front-end'}],
    },
    // Back-End
    {
      type: 'category',
      label: 'Back-End',
      items: [{type: 'autogenerated', dirName: 'back-end'}],
    },
    // Base de Datos
    {
      type: 'category',
      label: 'Data Base',
      items: [{type: 'autogenerated', dirName: 'base-de-datos'}],
    },
  ],
};

export default sidebars;
