import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  manualSidebar: [
    {
      type: 'category',
      label: 'Manual de Usuario',
      items: [{type: 'autogenerated', dirName: '.'}],
    },
  ],
};

export default sidebars;